# Generated by Django 5.2.8 on 2025-12-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0005_subscriptionplan_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='articles',
            field=models.CharField(blank=True, null=True, verbose_name='وضعیت مقالات'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='private_projects',
            field=models.CharField(blank=True, null=True, verbose_name='وضعیت پروژه های خصوصی'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='questions',
            field=models.CharField(blank=True, null=True, verbose_name='وضعیت پرسش ها'),
        ),
    ]
