# Generated by Django 5.2.8 on 2025-12-12 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('pricing', '0008_alter_discountitem_min_price_discountcodeusage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountitem',
            name='product',
        ),
        migrations.AddField(
            model_name='discountitem',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discountitem',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('subscription', 'اشتراک'), ('course', 'دوره')], max_length=20),
        ),
    ]
