# Generated by Django 5.2.8 on 2025-12-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0009_remove_discountitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('subscription', 'اشتراک')], max_length=20),
        ),
    ]
