# Generated by Django 5.2.8 on 2025-12-15 14:28

import apps.pricing.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0010_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='موضوع')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.pricing.models.course_thumbnail_upload_path, verbose_name='تصویر بند انگشتی')),
                ('preview', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='پیش نمایش')),
                ('paid_type', models.CharField(choices=[('paid', 'تمام پولی'), ('semi_paid', 'نیمه پولی'), ('free', 'رایگان')], verbose_name='نوع قیمت دوره')),
                ('course_type', models.CharField(choices=[('basic', 'مقدماتی'), ('advanced', 'پیشرفته'), ('basic2advanced', 'مقدماتی تا پیشرفته'), ('02100', 'صفر تا صد')], verbose_name='نوع دوره')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('subscription', 'اشتراک'), ('course', 'دوره ها')], max_length=20),
        ),
    ]
