# Generated by Django 5.2.8 on 2025-12-15 14:43

import apps.pricing.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0011_course_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='موضوع')),
                ('slug', models.SlugField(unique=True, verbose_name='شناسه')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=apps.pricing.models.course_thumbnail_upload_path, verbose_name='تصویر بند انگشتی')),
                ('video', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])], verbose_name='ویدیو')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت')),
                ('attached_file', models.FileField(upload_to='', verbose_name='فایل ضمیمه')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.course', verbose_name='دوره')),
            ],
        ),
    ]
