# Generated by Django 5.2.8 on 2025-12-16 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0012_alter_course_price_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='مدرس'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('basic', 'مقدماتی'), ('advanced', 'پیشرفته'), ('basic2advanced', 'مقدماتی تا پیشرفته'), ('one2hundred', 'صفر تا صد')], verbose_name='نوع دوره'),
        ),
    ]
