# Generated by Django 5.2.8 on 2025-12-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0013_course_teacher_alter_course_course_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='private_projects',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='questions',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
