# Generated by Django 5.2.8 on 2026-01-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0014_remove_subscriptionplan_articles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='real_name',
            field=models.CharField(verbose_name='نام واقعی پلن'),
        ),
    ]
