# Generated by Django 5.2.8 on 2025-11-27 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_linkmodel_baselink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basecategory',
            options={'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب ها'},
        ),
    ]
