# Generated by Django 5.2.8 on 2025-11-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_basecategory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecomment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='محتوا'),
        ),
    ]
