# Generated by Django 5.2.8 on 2025-12-16 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_category_color'),
        ('social_django', '0017_usersocialauth_user_social_auth_uid_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociationProxy',
            fields=[
            ],
            options={
                'verbose_name': 'ارتباط OAuth',
                'verbose_name_plural': 'ارتباط\u200cهای OAuth',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social_django.association',),
        ),
        migrations.CreateModel(
            name='NonceProxy',
            fields=[
            ],
            options={
                'verbose_name': 'توکن موقت',
                'verbose_name_plural': 'توکن\u200cهای موقت',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social_django.nonce',),
        ),
        migrations.CreateModel(
            name='UserSocialAuthProxy',
            fields=[
            ],
            options={
                'verbose_name': 'حساب اجتماعی کاربر',
                'verbose_name_plural': 'حساب\u200cهای اجتماعی کاربران',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('social_django.usersocialauth',),
        ),
    ]
