# Generated by Django 5.2.8 on 2025-11-27 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_views'),
        ('core', '0002_linkmodel_baselink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('basecategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.basecategory')),
                ('slug', models.SlugField(verbose_name='شناسه')),
            ],
            bases=('core.basecategory',),
        ),
    ]
