# Generated by Django 5.2.8 on 2025-12-15 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_articlecategory_alter_article_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='articlecomment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_pin', True)), fields=('article',), name='unique_pinned_comment_per_article'),
        ),
    ]
