# Generated by Django 5.2.8 on 2025-12-18 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_articlecomment_unique_pinned_comment_per_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='بازدید ها'),
        ),
    ]
